package andrewjavastudy.demo.model;

public class Comments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENTS.ID
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENTS.PARENT_ID
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENTS.TYPE
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENTS.COMMENTATOR
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    private Long commentator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENTS.GMT_CREATE
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENTS.GMT_MODIFIED
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENTS.LIKE_COUNT
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    private Long likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENTS.CONTENT
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENTS.ID
     *
     * @return the value of COMMENTS.ID
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENTS.ID
     *
     * @param id the value for COMMENTS.ID
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENTS.PARENT_ID
     *
     * @return the value of COMMENTS.PARENT_ID
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENTS.PARENT_ID
     *
     * @param parentId the value for COMMENTS.PARENT_ID
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENTS.TYPE
     *
     * @return the value of COMMENTS.TYPE
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENTS.TYPE
     *
     * @param type the value for COMMENTS.TYPE
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENTS.COMMENTATOR
     *
     * @return the value of COMMENTS.COMMENTATOR
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    public Long getCommentator() {
        return commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENTS.COMMENTATOR
     *
     * @param commentator the value for COMMENTS.COMMENTATOR
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    public void setCommentator(Long commentator) {
        this.commentator = commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENTS.GMT_CREATE
     *
     * @return the value of COMMENTS.GMT_CREATE
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENTS.GMT_CREATE
     *
     * @param gmtCreate the value for COMMENTS.GMT_CREATE
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENTS.GMT_MODIFIED
     *
     * @return the value of COMMENTS.GMT_MODIFIED
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENTS.GMT_MODIFIED
     *
     * @param gmtModified the value for COMMENTS.GMT_MODIFIED
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENTS.LIKE_COUNT
     *
     * @return the value of COMMENTS.LIKE_COUNT
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENTS.LIKE_COUNT
     *
     * @param likeCount the value for COMMENTS.LIKE_COUNT
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENTS.CONTENT
     *
     * @return the value of COMMENTS.CONTENT
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENTS.CONTENT
     *
     * @param content the value for COMMENTS.CONTENT
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}