package andrewjavastudy.demo.model;

public class Questions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTIONS.ID
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTIONS.TITLE
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTIONS.GMT_CREATE
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTIONS.GMT_MODIFIED
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTIONS.CREATOR_ID
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTIONS.VIEW_COUNT
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTIONS.LIKE_COUNT
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTIONS.TAGS
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTIONS.DESCRIPTION
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTIONS.ID
     *
     * @return the value of QUESTIONS.ID
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTIONS.ID
     *
     * @param id the value for QUESTIONS.ID
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTIONS.TITLE
     *
     * @return the value of QUESTIONS.TITLE
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTIONS.TITLE
     *
     * @param title the value for QUESTIONS.TITLE
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTIONS.GMT_CREATE
     *
     * @return the value of QUESTIONS.GMT_CREATE
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTIONS.GMT_CREATE
     *
     * @param gmtCreate the value for QUESTIONS.GMT_CREATE
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTIONS.GMT_MODIFIED
     *
     * @return the value of QUESTIONS.GMT_MODIFIED
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTIONS.GMT_MODIFIED
     *
     * @param gmtModified the value for QUESTIONS.GMT_MODIFIED
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTIONS.CREATOR_ID
     *
     * @return the value of QUESTIONS.CREATOR_ID
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTIONS.CREATOR_ID
     *
     * @param creatorId the value for QUESTIONS.CREATOR_ID
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTIONS.VIEW_COUNT
     *
     * @return the value of QUESTIONS.VIEW_COUNT
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTIONS.VIEW_COUNT
     *
     * @param viewCount the value for QUESTIONS.VIEW_COUNT
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTIONS.LIKE_COUNT
     *
     * @return the value of QUESTIONS.LIKE_COUNT
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTIONS.LIKE_COUNT
     *
     * @param likeCount the value for QUESTIONS.LIKE_COUNT
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTIONS.TAGS
     *
     * @return the value of QUESTIONS.TAGS
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTIONS.TAGS
     *
     * @param tags the value for QUESTIONS.TAGS
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTIONS.DESCRIPTION
     *
     * @return the value of QUESTIONS.DESCRIPTION
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTIONS.DESCRIPTION
     *
     * @param description the value for QUESTIONS.DESCRIPTION
     *
     * @mbg.generated Sun Jan 19 16:02:50 HKT 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}