package andrewjavastudy.demo.mapper;

import andrewjavastudy.demo.model.Comments;
import andrewjavastudy.demo.model.CommentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENTS
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    long countByExample(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENTS
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    int deleteByExample(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENTS
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENTS
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    int insert(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENTS
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    int insertSelective(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENTS
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    List<Comments> selectByExampleWithRowbounds(CommentsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENTS
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    List<Comments> selectByExample(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENTS
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    Comments selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENTS
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    int updateByExampleSelective(@Param("record") Comments record, @Param("example") CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENTS
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    int updateByExample(@Param("record") Comments record, @Param("example") CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENTS
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    int updateByPrimaryKeySelective(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENTS
     *
     * @mbg.generated Sat Jan 11 22:07:17 HKT 2020
     */
    int updateByPrimaryKey(Comments record);
}