package andrewjavastudy.demo.mapper;

import andrewjavastudy.demo.model.Questions;
import andrewjavastudy.demo.model.QuestionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface QuestionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTIONS
     *
     * @mbg.generated Sun Jan 19 01:14:02 HKT 2020
     */
    long countByExample(QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTIONS
     *
     * @mbg.generated Sun Jan 19 01:14:02 HKT 2020
     */
    int deleteByExample(QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTIONS
     *
     * @mbg.generated Sun Jan 19 01:14:02 HKT 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTIONS
     *
     * @mbg.generated Sun Jan 19 01:14:02 HKT 2020
     */
    int insert(Questions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTIONS
     *
     * @mbg.generated Sun Jan 19 01:14:02 HKT 2020
     */
    int insertSelective(Questions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTIONS
     *
     * @mbg.generated Sun Jan 19 01:14:02 HKT 2020
     */
    List<Questions> selectByExampleWithBLOBsWithRowbounds(QuestionsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTIONS
     *
     * @mbg.generated Sun Jan 19 01:14:02 HKT 2020
     */
    List<Questions> selectByExampleWithBLOBs(QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTIONS
     *
     * @mbg.generated Sun Jan 19 01:14:02 HKT 2020
     */
    List<Questions> selectByExampleWithRowbounds(QuestionsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTIONS
     *
     * @mbg.generated Sun Jan 19 01:14:02 HKT 2020
     */
    List<Questions> selectByExample(QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTIONS
     *
     * @mbg.generated Sun Jan 19 01:14:02 HKT 2020
     */
    Questions selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTIONS
     *
     * @mbg.generated Sun Jan 19 01:14:02 HKT 2020
     */
    int updateByExampleSelective(@Param("record") Questions record, @Param("example") QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTIONS
     *
     * @mbg.generated Sun Jan 19 01:14:02 HKT 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Questions record, @Param("example") QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTIONS
     *
     * @mbg.generated Sun Jan 19 01:14:02 HKT 2020
     */
    int updateByExample(@Param("record") Questions record, @Param("example") QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTIONS
     *
     * @mbg.generated Sun Jan 19 01:14:02 HKT 2020
     */
    int updateByPrimaryKeySelective(Questions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTIONS
     *
     * @mbg.generated Sun Jan 19 01:14:02 HKT 2020
     */
    int updateByPrimaryKeyWithBLOBs(Questions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTIONS
     *
     * @mbg.generated Sun Jan 19 01:14:02 HKT 2020
     */
    int updateByPrimaryKey(Questions record);
}