package andrewjavastudy.demo.mapper;

import andrewjavastudy.demo.model.Questions;
import andrewjavastudy.demo.model.QuestionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface QuestionsExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTIONS
     *
     * @mbg.generated Thu Jan 09 19:04:48 HKT 2020
     */
    int incView(Questions record);
}